---
version: 1
schedule:
  type: simple
  interval: 1s 
# NOTE: fail fast for testing, not typical setting
max-failures: 1
workflow:
  collect:
    metrics:
      "/intel/psutil/load/load1": {}
      "/intel/psutil/load/load15": {}
      "/intel/psutil/load/load5": {}
      "/intel/psutil/vm/available": {}
      "/intel/psutil/vm/free": {}
      "/intel/psutil/vm/used": {}
      "/intel/psutil/cpu/*/user": {}
    publish:
    - plugin_name: graphite
      config:
        server: graphite
        port: 2003
        enable_tags: true
